/**
 * @file The root layout of the application
 */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
    title: "Portfolio Website",
    description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
    children: React.ReactNode;
}>;

/**
 * @param props - The props of the component
 * @returns The root layout of the application
 */
function RootLayout (props: RootLayoutProps): JSX.Element {
    const { children } = props;
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}

export default RootLayout;
export { metadata };